site_name: My Sketchy Docs

theme:
  name: material
  palette:
    - scheme: default   # 🔥 LIGHT THEME

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/ScrollToPlugin.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/ScrollTrigger.min.js
  - javascripts/extra.js

extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences