site_name: My Sketchy Docs

theme:
  name: material
  palette:
    - scheme: default
  features:
    - navigation.instant

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/ScrollToPlugin.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/ScrollTrigger.min.js
  - https://unpkg.com/rough-notation/lib/rough-notation.iife.js
  - javascripts/extra.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences